### ISSUE TITLE
does not display all codes in the delete and merge codes dialog boxes (web application)

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#114]
In the web app, when I want to delete or merge a code, it shows only the first code from my codebook. 
![image](https://user-images.githubusercontent.com/54745940/233405759-2620b6ff-9806-4583-ad2e-78983368ad70.png)
Applies to all server instances.

**Comment by hlageek** [comment]
Fixed by 6f3d235504b
 Apologies @skvrnami, I forgot to PR this.
