### ISSUE TITLE
Change colour of buttons in the Memo editing window

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#133]
Currently, in the memo editing window, there are three buttons: Close, Save & Close, Delete. Delete button is red, other two are grey. After editing, one tends to hit the coloured button as it is marked, and delete all previous work :-(  
I suggest to create either warning pop-up window asking for delete confirmation, or - easier - make Save & Close button green and the other two grey (unmarked).
![Snímek obrazovky z 2024-04-29 10-22-07](https://github.com/RE-QDA/requal/assets/54745940/46723192-04bf-42f9-b70c-33d9ea3b596e)

**Comment by hlageek** [comment]
Done, will ship a green memo button with the upcoming 1.1.2 dev version
