### ISSUE TITLE
document containing html code is displayed as a web page instead of plain text, causing a positional mismatch

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#143]
When a document containing html code is uploaded or created, Requal displays it as a web page, not plain text. E.g. `Home <index.php3>` will be displayed as `Home`. The html code is not shown. This disturbs the coding tool because the position of the coded segments in the following text does not match. 
![image](https://github.com/RE-QDA/requal/assets/54745940/ee195d01-f34f-4c86-a66f-8fc81aa2b8c7)
![image](https://github.com/RE-QDA/requal/assets/54745940/360f1c10-89aa-45c4-b3a4-66acb80aa638)
The html code in the data should be displayed as plain text in order to be coded correctly.

**Comment by hlageek** [comment]
Possible solution can be tested with `devtools::install_github(""RE-QDA/requal", branch = "issue-143"`.
