### ISSUE TITLE
rqda2requal()

### ISSUE THREAD

**Issue by hlageek** [RE-QDA/requal#45]
Since `RQDA` was instrumental in the `requal` development, I suggest we make a dedicated migration function that would allow `RQDA` users to move their projects into `requal`. The function would take the path to an existing `RQDA` file and a new `requal` project file as arguments and it would essentially be a script to rewrite `RQDA` data into `requal` DB scheme.  No need for UI, at least not at this stage, though we could provide an option to create new projects by import in the future, if we have more migrating scripts.

**Comment by skvrnami** [comment]
There is a working prototype in [feature/rqda_import](https://github.com/RE-QDA/requal/tree/feature/rqda_import).
However, I need some examples of projects created with `RQDA` for testing it. @martin-hajek, could you send me some?
I could use the RQDA files students coded for testing inter-coding reliability, but I am not sure if these are representative for full-fledged projects created with RQDA.
