### ISSUE TITLE
triage: procedure for deciding on functions/features

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#53]
We don't have any formal procedure for deciding which function, feature, or design element should or shouldn't be implemented (triage). Potentially, there is an infinite number of what could be added to the program or improved in it, but there is a limited amount of our time to do it and, more importantly, not everything would make the program better. Drawing on [established project](https://www.chromium.org/for-testers/bug-reporting-guidelines/triage-best-practices/) and after a preliminary discussion in our team, I propose these arrangments:

1. every element of the program is open to discussion and can be implemented, changed or removed; there are no "matter-of-course" functions, features or designs;
2. proposals for new elements shall have a form of issue, and every member can express their opinion; if no objection is raised during two weeks, the element is considered accepted and should be implemented; if anyone objects, the element is discussed until the team takes collective decision; 
3. the decision about each element has to be consensual within a team; nobody has a power of veto;
4. any element which has not passed through this procedure (consensually accepted issue) shall be removed from the program if a team member asks for it.

**Comment by hlageek** [comment]
I think this issue should be raised in the docs repo, not here.

**Comment by martin-hajek** [comment]
I thought that having it in a public repository would increase the transparency and reproducibility of our project. But I agree that we can first start a private discussion and then make the result public.
