### ISSUE TITLE
applying another code over a coded segment (exact match) creates code extension

### ISSUE THREAD

**Issue by martin-hajek** [RE-QDA/requal#71]
If the coded segment is re-coded with a different code, the marked text is extended to the rest of the document. When you hover over the extended segment, both codes are displayed correctly, but the deletion does not work. To remove the extended segment, you must click on the original overlapping segment.
This only happens if the codes are applied to exactly the same segment.

https://user-images.githubusercontent.com/54745940/159051009-46739252-3cb4-43ec-b59c-d7c77c8d667b.mp4

**Comment by hlageek** [comment]
Possibly related to #64

**Comment by hlageek** [comment]
patched by https://github.com/RE-QDA/requal/pull/73
